#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page
# that contains the string Hello World!

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Create a file with "Hello World!"
echo 'Hello World' | sudo tee /var/www/html/index.html

# Start Nginx
sudo service nginx start
