#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

apt-get update -y 
apt-get install nginx -y 
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "hello world!" > /var/www/html/index.html'
service nginx restart
