#!/usr/bin/env bash
# Configures an nginx server so that /redirect_me redirects to a new page
# redirect Nginx server to another page
# The redirection type is 301-Moved Permanently 

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sed -i  '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4  permanent;' /etc/nginx/sites-available/default

sh -c 'echo "Hello World!" > /var/www/html/index.html' 
sudo service nginx restart
