#!/usr/bin/env bash
# Configures an nginx server so that /redirect_me redirects to a new page
# redirect Nginx server to another page
# The redirection type is 301-Moved Permanently 

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

buffer="server_name _;\n\trewrite ^\/redirect_me https:\/\/twitter.com permanent;"
sudo sed -i "s/server_name _;/$buffer/" /etc/nginx/sites-available/default

sudo echo <<< "Ceci n'est pas une page" > /var/www/html/404.html

buffer_2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$buffer_2/" /etc/nginx/sites-available/default
 
sh -c 'echo "Hello World!" > /var/www/html/index.html' 
sudo service nginx restart
