#!/usr/bin/env bash
#What is the OSI model and How is the OSI model organized?
3. The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology
4. From the lowest to the highest level