#!/usr/bin/env bash

# A Bash script that configures an Ubuntu server

cp /etc/hosts ~/hosts.new

echo "127.0.0.1 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

sudo cp -f ~/hosts.new /etc/hosts